### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by mhdhejazi** [klassen-software-solutions/KSSDiff#6]
Thank you for porting diff-match-patch to Swift!

I tried using the package in an iOS app and got multiple errors. It'd be great if the package also supports iOS in addition to the existing macOS support.

**Comment by stevenklassen8376** [comment]
That shouldn’t be too tough. I’ll see if I can find some time in the next week.

**Comment by mhdhejazi** [comment]
Well, there were two kinds of errors:
1. iOS version issues.
Can be solved by changing the minimum supported iOS version.
2. XMLDocument library not found as it's only available on macOS and some classes in KSSCore use this library.
Not sure how to solve this. Looks like the decision to depend on KSSCore needs to be reviewed.

**Comment by stevenklassen8376** [comment]
Step one is completed. KSSCore has been updated to support iOS. Tomorrow I will do the same for this library.

**Comment by stevenklassen8376** [comment]
This has been added in version 1.0.3.

**Comment by mhdhejazi** [comment]
Great! Thank you for your hard work.

**Comment by stevenklassen8376** [comment]
You are welcome.
